### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by flytigerzhang** [larrycai/xin2pbn#5]
D:\feihu\SynologyDrive\桥牌\软件>xin2pbn.exe "http://www.xinruibridge.com/deallog/DealLog.html?bidlog=3S,P;4S,P,P,P;&playlog=E:TH,JH,AH,7H;W:JD,QD,KD,AD;S:8S,7S,AS,3S;N:KS,JS,9S,QS;N:8H,2H,KH,7C;S:QH,5C,5D,9H;S:4H,8C,2S,6H;N:TS,2C,3D,6D;N:6S,2D,7D,TC;N:5S,JC,4C,8D;N:4S,9C,3H,TD;N:#1111&deal=AKT6542.87.Q95.3%20J3.T9652.K42.J92%2098.KQJ43.A73.A64%20Q7.A.JT86.KQT875&vul=EW&dealer=N&contract=4S&declarer=N&wintrick=12&score=480&dealid=1322942418&pbnid=110884683&str=%E6%AF%8F%E6%97%A5MP%E8%B5%9B20220523%20%E7%89%8C%E5%8F%B7%209/12"
Traceback (most recent call last):
  File "C:\Users\feihu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\feihu\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\feihu\SynologyDrive\桥牌\软件\xin2pbn.exe\__main__.py", line 7, in <module>
  File "C:\Users\feihu\AppData\Local\Programs\Python\Python38\lib\site-packages\xin2pbn\xin2pbn.py", line 127, in main
    xin2pbn(param[0], PBN_FILE)
  File "C:\Users\feihu\AppData\Local\Programs\Python\Python38\lib\site-packages\xin2pbn\xin2pbn.py", line 78, in xin2pbn
    all["leader"] = DECLARE2LEADER[all["declarer"]]
KeyError: 'declarer'

**Comment by larrycai** [comment]
thank for reporting, quick fix (not perfect)

````
pip install upgrade xin2pbn # 0.1.17
````

let me know if it works
